### ISSUE TITLE
 writing problems on the SD

### ISSUE THREAD

**Issue by misterjbam** [RBSC/Carnivore2Plus#10]
Good morning
I have a writing problem with the SD which prevents Sofarun from working properly.
I tried with another SD, same problem.
I tested with a CF and no problems.

**Comment by Wierzbowsky** [comment]
Are you using TurboR or MSX2+ machine by any chance? We found some issues with SD writing on these machines. Please try this beta firmware - it should fix these issues.
[beta_firmware.zip](https://github.com/user-attachments/files/15941991/beta_firmware.zip)

**Comment by misterjbam** [comment]
I use a turboR
thanks for the firmware, I will test it soon

**Comment by misterjbam** [comment]
I updated to 3.02 and I no longer have problems with the SD on my turbo-R
THANKS
