### ISSUE TITLE
 no way to flash i-logic game

### ISSUE THREAD

**Issue by misterjbam** [RBSC/Carnivore2Plus#13]
Good morning

I tried a lot of solutions, but I can't get the i-logic game to work when flashing with cman

no problem with the rom on another flashcard

http://www.plattysoft.com/msx/i-logic/

**Comment by Wierzbowsky** [comment]
This is a 49kb ROM and looks like C2MAN incorrectly identifies it.
Please delete the old game's ROM from Carnivore2's FlashROM, rename your game's ROM file to I-LOGIC.ROM and copy the RCP file from the attached archive into the same folder with your game's ROM. Then flash the game using C2MAN utility into your Carnivore2 and answer "Yes" when asked whether to use the RCP file.
[I-LOGIC.zip](https://github.com/user-attachments/files/17062529/I-LOGIC.zip)

**Comment by misterjbam** [comment]
Many thanks for your responsiveness in responding.
The game now works perfectly on Carnivore 2+

THANK YOU
